/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V2OnboardingRouteImport } from './routes/v2.onboarding'
import { Route as V2OnboardingIndexRouteImport } from './routes/v2.onboarding.index'
import { Route as V2OnboardingStepRouteImport } from './routes/v2.onboarding.$step'
import { Route as ComplianceCaseCaseIdRouteImport } from './routes/compliance.case.$caseId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2OnboardingRoute = V2OnboardingRouteImport.update({
  id: '/v2/onboarding',
  path: '/v2/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const V2OnboardingIndexRoute = V2OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2OnboardingRoute,
} as any)
const V2OnboardingStepRoute = V2OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => V2OnboardingRoute,
} as any)
const ComplianceCaseCaseIdRoute = ComplianceCaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => ComplianceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/v2/onboarding': typeof V2OnboardingRouteWithChildren
  '/compliance/case/$caseId': typeof ComplianceCaseCaseIdRoute
  '/v2/onboarding/$step': typeof V2OnboardingStepRoute
  '/v2/onboarding/': typeof V2OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/compliance/case/$caseId': typeof ComplianceCaseCaseIdRoute
  '/v2/onboarding/$step': typeof V2OnboardingStepRoute
  '/v2/onboarding': typeof V2OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/v2/onboarding': typeof V2OnboardingRouteWithChildren
  '/compliance/case/$caseId': typeof ComplianceCaseCaseIdRoute
  '/v2/onboarding/$step': typeof V2OnboardingStepRoute
  '/v2/onboarding/': typeof V2OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/onboarding'
    | '/v2/onboarding'
    | '/compliance/case/$caseId'
    | '/v2/onboarding/$step'
    | '/v2/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/onboarding'
    | '/compliance/case/$caseId'
    | '/v2/onboarding/$step'
    | '/v2/onboarding'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/onboarding'
    | '/v2/onboarding'
    | '/compliance/case/$caseId'
    | '/v2/onboarding/$step'
    | '/v2/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  V2OnboardingRoute: typeof V2OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/onboarding': {
      id: '/v2/onboarding'
      path: '/v2/onboarding'
      fullPath: '/v2/onboarding'
      preLoaderRoute: typeof V2OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/onboarding/': {
      id: '/v2/onboarding/'
      path: '/'
      fullPath: '/v2/onboarding/'
      preLoaderRoute: typeof V2OnboardingIndexRouteImport
      parentRoute: typeof V2OnboardingRoute
    }
    '/v2/onboarding/$step': {
      id: '/v2/onboarding/$step'
      path: '/$step'
      fullPath: '/v2/onboarding/$step'
      preLoaderRoute: typeof V2OnboardingStepRouteImport
      parentRoute: typeof V2OnboardingRoute
    }
    '/compliance/case/$caseId': {
      id: '/compliance/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/compliance/case/$caseId'
      preLoaderRoute: typeof ComplianceCaseCaseIdRouteImport
      parentRoute: typeof ComplianceRoute
    }
  }
}

interface ComplianceRouteChildren {
  ComplianceCaseCaseIdRoute: typeof ComplianceCaseCaseIdRoute
}

const ComplianceRouteChildren: ComplianceRouteChildren = {
  ComplianceCaseCaseIdRoute: ComplianceCaseCaseIdRoute,
}

const ComplianceRouteWithChildren = ComplianceRoute._addFileChildren(
  ComplianceRouteChildren,
)

interface V2OnboardingRouteChildren {
  V2OnboardingStepRoute: typeof V2OnboardingStepRoute
  V2OnboardingIndexRoute: typeof V2OnboardingIndexRoute
}

const V2OnboardingRouteChildren: V2OnboardingRouteChildren = {
  V2OnboardingStepRoute: V2OnboardingStepRoute,
  V2OnboardingIndexRoute: V2OnboardingIndexRoute,
}

const V2OnboardingRouteWithChildren = V2OnboardingRoute._addFileChildren(
  V2OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  V2OnboardingRoute: V2OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
